services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # vm-be host-only IP: 192.168.56.103
        # Untuk production, ganti dengan: https://api.yourdomain.com/api
        NEXT_PUBLIC_API_URL: http://192.168.56.103/api
    container_name: nopmo_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
